# Generated by Django 5.2.14 on 2026-06-02 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('check_interval', models.PositiveIntegerField(default=5, help_text='Check interval in minutes')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Timeout in seconds')),
                ('notify_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in ms', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uptime_percentage', models.FloatField(default=0.0)),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('successful_checks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('error', 'Error')], max_length=10)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in ms', null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.website')),
            ],
            options={
                'verbose_name': 'Monitor Check',
                'verbose_name_plural': 'Monitor Checks',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='critical', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitors.website')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-started_at'],
            },
        ),
    ]
